name: Build OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  models: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build prompt with code context
      run: |
        echo 'Try to give fixes to any bugs that may occur.' > context.txt

        for file in \
          kernel.c \
          syscalls.h \
          posix/posix.h \
          helpers/basics.h
        do
          echo '```c' >> context.txt
          cat "$file" >> context.txt
          echo '```' >> context.txt
        done
    - name: Load prompt into env var
      id: load
      run: |
        prompt="$(cat context.txt)"
        echo "PROMPT<<EOF" >> $GITHUB_OUTPUT
        echo "$prompt" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Call GitHub AI model
      uses: actions/ai-inference@v1
      with:
        prompt: ${{ steps.load.outputs.PROMPT }}

    - name: Show response
      run: echo "${{ steps.inference.outputs.response }}"
    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          OS/*.o
          OS/kernel
        key: ${{ runner.os }}-os-build-${{ hashFiles('**/*.c', '**/*.asm', 'Makefile') }}
        restore-keys: |
          ${{ runner.os }}-os-build-

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-multilib grub-pc-bin xorriso nasm qemu-system-i386 mtools

    - name: Create 10MB empty disk
      run: dd if=/dev/zero of=disk.img bs=1M count=10

    - name: Build the ISO
      run: make

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      
      with:
        name: os.iso
        path: os.iso

